version: "3"

networks:

  default:
    name: geth_mainnet

  prometheus:
    external:
      name: prometheus

services:

  geth:
    container_name: geth_mainnet
    dns: [ 192.168.1.1 ] # unbound
    image: ethereum/client-go:stable
    restart: unless-stopped
    command:
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.corsdomain=moz-extension://0d6948d6-4cab-4438-83f5-b74012565eb3 # MetaMask
      - --http.port=8545 # default 8545
      - --http.vhosts=geth_mainnet
      - --identity=${IDENTITY}
      - --ipcpath=/root/.ethereum/geth.ipc
      - --log.debug=true
      - --metrics # /debug/metrics/prometheus
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060 # default 6060
      - --port=30303 # default 30303
      - --syncmode=fast
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - prometheus
    ports:
      - 8545:8545 # rcp
      - 30303:30303 # p2p
    volumes:
      - geth:/root/.ethereum
      - powchain:/data

volumes:

  geth:
    name: geth_mainnet

  powchain:
    driver: local
    driver_opts:
      device: :/Geth
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
