version: "3"

networks:

  default:
    name: polkadot-net

  prometheus-net:
    external:
      name: prometheus-net

  traefik-net:
    external:
      name: traefik-net

services:

  polkadot:
    container_name: polkadot
    image: parity/polkadot:latest
    restart: unless-stopped
    command:
      - --chain=polkadot
      - --name PolkaDocker
      - --rpc-cors all
      - --rpc-external
      - --ws-external
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 30G
    ports:
      - 30333:30333 # p2p
      - 9615:9615 # monitoring
      - 9933:9933 # rpc
      - 9944:9944 # ws
    volumes:
      - polkadot:/polkadot

  polkadotui:
    container_name: polkadotui
    image: jacogr/polkadot-js-apps:latest
    restart: unless-stopped
    environment:
      WS_URL: ws://polkadot:9944
    labels:
      traefik.enable: true
      traefik.http.services.polkadotui.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net

volumes:

  polkadot:
    driver: local
    driver_opts:
      device: :/Polkadot
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
