version: "3"

networks:

  default:
    name: polkadot-net

  prometheus-net:
    external:
      name: prometheus-net

services:

  polkadot:
    container_name: polkadot
    dns: [ 192.168.1.1 ]
    image: parity/polkadot:latest
    restart: unless-stopped
    command:
      - --chain=polkadot
      - --in-peers=50
      - --name=PolkaMcDotFace
      - --out-peers=50
      - --port=30333 # default 30333
      - --prometheus-external
      - --prometheus-port=9615 # default 9615
      - --pruning=archive
      - --rpc-cors=all
      - --rpc-port=9933 # default 9933
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --ws-port=9944 # default 9944
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 16G
    networks:
      - default
      - prometheus-net
    ports:
      - 9944:9944 # ws
      - 30333:30333 # p2p
    volumes:
      - polkadot:/polkadot

volumes:

  polkadot:
    driver: local
    driver_opts:
      device: :/Polkadot
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
