version: '3'

networks:

  default:
    name: wallabag

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: wallabag-db
    image: mariadb:10.6.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${MYSQL_USER}"
    volumes:
      - ./db:/var/lib/mysql

  redis:
    container_name: wallabag-redis
    image: redis:6.2.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis:/data

  wallabag:
    container_name: wallabag
    image: wallabag/wallabag:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: wallabag-db
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: "${WALLABAG_PASSWORD}"
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${DOMAIN}
      SYMFONY__ENV__FROM_EMAIL: wallabag@${DOMAIN}
      SYMFONY__ENV__REDIS_HOST: wallabag-redis
      SYMFONY__ENV__SERVER_NAME: Wallabag
    labels:
      traefik.enable: true
      traefik.http.routers.wallabag-api.rule: Host(`wallabag.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.wallabag.middlewares: authelia, error-pages
      traefik.http.services.wallabag.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./images:/var/www/wallabag/web/assets/images

volumes:

  redis:
    name: wallabag-redis
