version: "3"

networks:

  default:
    name: eth-net

  prometheus-net:
    external:
      name: prometheus-net

  traefik-net:
    external:
      name: traefik-net

services:

  geth:
    container_name: geth
    image: ethereum/client-go:stable
    restart: unless-stopped
    command:
      # - --log.debug=true
      - --datadir=/data
      - --identity=Nodey
      - --ipcpath=/root/.ethereum/geth.ipc
      - --maxpeers=50
      - --metrics # /debug/metrics/prometheus
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --syncmode=fast
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 16G
    networks:
      - default
      - prometheus-net
    ports:
      - 30303:30303
    volumes:
      - ./config:/root/.ethereum
      - geth:/data

  prysm-beacon:
    container_name: prysm-beacon
    image: prysmaticlabs/prysm-beacon-chain:stable
    restart: unless-stopped
    depends_on:
      geth:
        condition: service_started
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --fallback-web3provider=
      - --force-clear-db
      - --http-web3provider="http://geth:8545"
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8080 # /metrics
      - --p2p-host-dns=
      - --p2p-max-peers=50
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --verbosity=info
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 16G
    networks:
      - default
      - prometheus-net
    ports:
      - 12000:12000
      - 13000:13000
      - 4000:4000
    volumes:
      - beacon:/data

  prysm-validator:
    container_name: prysm-validator
    image: prysmaticlabs/prysm-validator:stable
    restart: unless-stopped
    command:
      - --accept-terms-of-use
      - --beacon-rpc-provider="prysm-beacon:4000"
      - --graffiti=
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=7500
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8081 # /metrics
      - --rpc-host=localhost
      - --rpc-port=7000
      - --verbosity=info
      - --web
    depends_on:
      prysm-beacon:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 16G
    labels:
      traefik.enable: true
      traefik.http.routers.prysm.middlewares: authelia, error-pages, whitelist-lan@file
      traefik.http.routers.prysm.rule: "Host(`prysm.${DOMAIN}`)"
      traefik.http.services.prysm.loadbalancer.server.port: 7500
    networks:
      - default
      - prometheus-net
      - traefik-net

volumes:

  beacon:
    driver: local
    driver_opts:
      device: :/Beacon
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  geth:
    driver: local
    driver_opts:
      device: :/Geth
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
