version: "3"

services:

  samba:
    container_name: samba
    image: servercontainers/samba:latest
    network_mode: host
    restart: unless-stopped
    environment:
      ACCOUNT_pi: "${PASSWORD}"
      AVAHI_NAME: RASPBERRYPI
      SAMBA_CONF_WORKGROUP: WORKGROUP
      SAMBA_GLOBAL_CONFIG_1: "browseable = yes"
      SAMBA_GLOBAL_CONFIG_2: "guest ok = no"
      SAMBA_GLOBAL_CONFIG_3: "read only = no"
      SAMBA_GLOBAL_CONFIG_4: "valid users = pi"
      SAMBA_VOLUME_CONFIG_BOOKS:  "[Books];  path=/books"
    volumes:
      - /etc/avahi/services:/external/avahi
      - /mnt/ssd1/calibre:/movies
