version: "3"

networks:

  default:
    name: qbittorrent

  traefik:
    external:
      name: traefik

services:

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.middlewares: authelia, error-pages
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
    volumes:
      - ./qbittorrent:/config
      - downloads:/downloads

  gluetun:
    container_name: qbittorrent-vpn
    image: qmcgaw/gluetun:v3.18.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      BLOCK_ADS: "on"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "on"
      DOT: "on"
      DOT_CACHING: "on"
      DOT_PROVIDERS: quad9
      FIREWALL: "on"
      FIREWALL_INPUT_PORTS: 9091
      FIREWALL_VPN_INPUT_PORTS: "${TORRENT_PORT_FORWARD}"
      OPENVPN_USER: "${OPENVPN_USER}"
      OPENVPN_VERBOSITY: 2
      PGID: "${PGID}"
      PUID: "${PUID}"
      SERVER_HOSTNAME: "${SERVER_HOSTNAME}"
      TZ: "${TZ}"
      VPNSP: mullvad
    networks:
      - default
      - traefik
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ./gluetun:/gluetun

volumes:

  downloads:
    name: downloads
