version: "3"

networks:

  default:
    name: prysm_mainnet

  prometheus:
    external:
      name: prometheus

  traefik:
    external:
      name: traefik

services:

  beacon:
    dns: [ 192.168.1.1 ] # unbound
    image: prysmaticlabs/prysm-beacon-chain:stable
    restart: unless-stopped
    command:
      - --accept-terms-of-use
      - --datadir=/data
      # - --fallback-web3provider=https://mainnet.infura.io/v3/${INFURA_PROJECT},Basic ${INFURA_SECRET}
      - --grpc-gateway-host=0.0.0.0 # default 127.0.0.1
      - --grpc-gateway-port=3500 # default 3500
      - --http-web3provider=/geth/geth.ipc
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8080 # default 8080/metrics
      - --p2p-tcp-port=13000 # default 13000
      - --p2p-udp-port=12000 # default 12000
      - --rpc-host=0.0.0.0 # default 0.0.0.0
      - --rpc-port=4000 # default 4000
      - --verbosity=debug # info,debug,trace; default info
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G # 16G recommended for Prysm
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - prometheus
    ports:
      - 12000:12000 # p2p udp
      - 13000:13000 # p2p tcp
    volumes:
      - beaconchain:/data
      - geth:/geth

  validator:
    dns: [ 192.168.1.1 ] # unbound
    image: prysmaticlabs/prysm-validator:stable
    restart: unless-stopped
    command:
      - --accept-terms-of-use
      - --beacon-rpc-gateway-provider=beacon:3500
      - --beacon-rpc-provider=beacon:4000
      - --datadir=/data
      - --graffiti=${GRAFFITI}
      - --grpc-gateway-host=0.0.0.0 # default 127.0.0.1
      - --grpc-gateway-port=7500 # default 7500
      - --monitoring-host=0.0.0.0 # default 127.0.0.1
      - --monitoring-port=8081 # /metrics
      - --rpc-host=0.0.0.0 # default 127.0.0.1
      - --rpc-port=7000 # default 7000
      - --verbosity=debug # default info
      - --wallet-dir=/data/wallet
      - --web
      - --write-wallet-password-on-web-onboarding
    depends_on:
      beacon:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G # 16G recommended for Prysm
    labels:
      traefik.enable: true
      traefik.http.routers.prysm-mainnet-api.middlewares: whitelist-lan@file
      traefik.http.routers.prysm-mainnet-api.rule: Host(`prysm-testnet.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.prysm-mainnet.middlewares: authelia, error-pages, whitelist-lan@file
      traefik.http.routers.prysm-mainnet.rule: "Host(`prysm-mainnet.${DOMAIN}`)"
      traefik.http.services.prysm-mainnet.loadbalancer.server.port: 7500
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - prometheus
      - traefik
    volumes:
      - ./prysm:/data

volumes:

  beaconchain:
    driver: local
    driver_opts:
      device: :/Beacon
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  geth:
    external: true
    name: geth_mainnet

  powchain:
    external: true
    name: geth_mainnet_powchain
