version: "3"

networks:

  default:
    name: geth_testnet

  prometheus:
    external:
      name: prometheus

services:

  geth:
    container_name: geth_testnet
    dns: [ 192.168.1.1 ] # unbound
    image: ethereum/client-go:latest
    restart: unless-stopped
    command:
      - --datadir=/data
      - --goerli # testnet
      - --http
      - --http.addr=0.0.0.0
      - --http.corsdomain=moz-extension://0d6948d6-4cab-4438-83f5-b74012565eb3 # MetaMask
      - --http.port=8546 # default 8545
      - --http.vhosts=*
      - --identity=${IDENTITY}
      - --ipcpath=/root/.ethereum/geth.ipc
      - --log.debug=true
      - --metrics # /debug/metrics/prometheus
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060 # default 6060
      - --port=30304 # default 30303
      - --syncmode=fast
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G # 16G+ recommended
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - prometheus
    ports:
      - 30304:30304 # p2p
    volumes:
      - geth:/root/.ethereum
      - powchain:/data

volumes:

  geth:
    name: geth_testnet

  powchain:
    driver: local
    driver_opts:
      device: :/Geth_Goerli
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
