version: "3"

networks:

  default:
    name: bitwarden-net

  traefik-net:
    external:
      name: traefik-net

services:

  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
    labels:
      traefik.enable: true
      traefik.http.routers.bitwarden.middlewares: lan-only
      traefik.http.services.bitwarden.loadbalancer.service.port: 80
    networks:
      - default
      - traefik-net
