version: "3"

networks:

  default:
    name: bitwarden

  traefik:
    external:
      name: traefik

services:

  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      SIGNUPS_ALLOWED: "false"
      WEBSOCKET_ENABLED: "true"
    labels:
      traefik.enable: true
      traefik.http.routers.bitwarden.middlewares: authelia, error-pages, lan-only
      traefik.http.services.bitwarden.loadbalancer.service.port: 80
    networks:
      - default
      - traefik
