version: "3"

services:

  fail2ban:
    container_name: fail2ban
    image: crazymax/fail2ban:0.11.2
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      F2B_DB_PURGE_AGE: 1d
      F2B_LOG_LEVEL: DEBUG
      F2B_LOG_TARGET: /var/log/fail2ban/fail2ban.log
      SSMTP_HOST: "${SSMTP_HOST}"
      SSMTP_PASSWORD: "${SSMTP_PASSWORD}"
      SSMTP_PORT: 587
      SSMTP_STARTTLS: "YES"
      SSMTP_USER: "${SSMTP_USER}"
      TZ: "${TZ}"
    volumes:
      - ./data:/data
      - /var/log/fail2ban:/var/log/fail2ban
      - /var/log:/var/log:ro
