version: "3"

services:

  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI
      - 8266:8266 # server
      - 8267:8267 # node
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      serverIP: 0.0.0.0
      serverPort: 8266
      TZ: "${TZ}"
      UMASK_SET: 002
      webUIPort: 8265
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media

  tdarr-node:
    container_name: tdarr-node
    image: haveagitgat/tdarr_node:latest
    network_mode: service:tdarr
    restart: unless-stopped
    environment:
      nodeID: MainNode
      nodeIP: 0.0.0.0
      nodePort: 8267
      PGID: ${"PGID"}
      PUID: ${"PUID"}
      serverIP: 0.0.0.0
      serverPort: 8266
      TZ: "${TZ}"
      UMASK_SET: 002
    volumes:
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media
