version: "3"

networks:

  default:
    name: teku_testnet

  geth_testnet:
    external:
      name: geth_testnet

  prometheus:
    external:
      name: prometheus

services:

  teku:
    container_name: teku_testnet
    dns: [ 192.168.1.1 ]
    image: consensys/teku:latest
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G
    environment:
      JAVA_OPTS: -Xmx4g
      TEKU_DATA_BEACON_PATH: /beaconchain
      TEKU_ETH1_ENDPOINTS: http://geth_testnet:8546, ${INFURA_URL}
      TEKU_LOGGING: INFO
      TEKU_METRICS_ENABLED: "true"
      TEKU_METRICS_HOST_ALLOWLIST: teku_testnet
      TEKU_METRICS_INTERFACE: 0.0.0.0
      TEKU_NETWORK: pyrmont
      TEKU_P2P_PORT: 9001
      TEKU_REST_API_DOCS_ENABLED: "true"
      TEKU_REST_API_ENABLED: "true"
      TEKU_VALIDATOR_KEYS: /validator/keys:/validator/passwords/
      TEKU_VALIDATORS_GRAFFITI: "${GRAFFITI}"
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - geth_testnet
      - prometheus
    ports:
      - 9001:9001 # p2p
      - 5051:5051
    volumes:
      - ./validator:/validator
      - beaconchain:/beaconchain

volumes:

  beaconchain:
    driver: local
    driver_opts:
      device: :/Teku_Pyrmont
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
