version: "3"

networks:

  default:
    name: heimdall-net

  traefik-net:
    external:
      name: traefik-net

services:

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.middlewares: authelia
      traefik.http.services.heimdall.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./config:/config
