version: "3"

networks:

  default:
    name: cops-net

  traefik-net:
    external:
      name: traefik-net

services:
  cops:
    container_name: cops
    image: linuxserver/cops:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.cops-opds.rule: Host(`cops.${DOMAIN}`) && Path(`/feed.php`)
      traefik.http.routers.cops.middlewares: authelia
      traefik.http.services.cops.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./config:/config
      - books:/books

volumes:

  books:
    driver: local
    driver_opts:
      device: :/Books
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
