version: "3"

networks:

  default:
    name: plex

  traefik:
    external:
      name: traefik

services:

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    environment:
      PGID: ${PGID}
      PLEX_CLAIM: ${PLEX_CLAIM}
      PUID: ${PUID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.plex.middlewares: lan-only
      traefik.http.services.plex.loadbalancer.server.port: 32400
    networks:
      - default
      - traefik
    ports:
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32400:32400
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - "./config:/config/Library/Application Support/Plex Media Server"
      - multimedia:/data

volumes:

  multimedia:
    driver: local
    driver_opts:
      device: ":/Multimedia"
      o: nfsvers=4,addr=192.168.1.3,rw
      type: nfs
