version: "3"

networks:

  default:
    name: traccar

  traefik:
    external:
      name: traefik

services:

  traccar:
    container_name: traccar
    image: traccar/traccar:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.traccar.middlewares: error-pages
      traefik.http.services.traccar.loadbalancer.server.port: 8082
    networks:
      - default
      - traefik
    volumes:
      - ./data:/opt/traccar/data
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - /var/log/traccar:/opt/traccar/logs
      - gpx:/gpx

volumes:

  gpx:
    external:
      name: gpx
