version: "3"

networks:

  default:
    name: piwigo

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: piwigo-db
    image: mariadb:10.6.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${MYSQL_USER}"
    volumes:
      - ./db:/var/lib/mysql

  piwigo:
    container_name: piwigo
    image: linuxserver/piwigo:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.piwigo.middlewares: error-pages
      traefik.http.services.piwigo.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./config:/config
      - photos:/gallery

volumes:

  photos:
    external:
      name: photos
