version: "3"

networks:

  default:
    name: monero

services:

  monerod:
    container_name: monerod
    image: xmrto/monero:v0.17.2.0
    restart: unless-stopped
    command:
      - "--rpc-login=${RPC_USER}:${RPC_PASSWORD}"
    deploy:
      resources:
        limits:
          cpus: 2 # 2 recommended
          memory: 4G # 4G+ recommended
    environment:
      LOG_LEVEL: 1
      P2P_BIND_PORT: 18080 # default 18080
      RPC_BIND_PORT: 18081 # default 18081
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
    ports:
      - 18080:18080 # p2p
      - 18081:18081 # rpc
    volumes:
      - ./bitmonero.conf:/data/bitmonero.conf:ro
      - monero:/monero

volumes:

  monero:
    driver: local
    name: monero
    driver_opts:
      device: :/Monero
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
