version: "2"

networks:

  default:
    name: monero-net

services:

  monerod:
    container_name: monerod
    image: xmrto/monero:v0.17.2.0
    restart: unless-stopped
    command:
      - --data-dir=/data
      - --in-peers=50
      - --out-peers=50
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4G
    environment:
      LOG_LEVEL: 1
      P2P_BIND_PORT: 18080 # default 18080
      RPC_BIND_PORT: 18081 # default 18081
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 18080:18080 # p2p
      - 18081:18081 # rpc
    volumes:
      - ./bitmonero.conf:/data/bitmonero.conf:ro
      - monero:/data

volumes:

  monero:
    driver: local
    name: monero
    driver_opts:
      device: :/Monero
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
