version: "2"

networks:

  default:
    name: monero-net

services:

  gluetun:
    container_name: monero-vpn
    image: qmcgaw/gluetun:v3.18.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      BLOCK_ADS: "on"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "on"
      DOT: "on"
      DOT_CACHING: "on"
      DOT_PROVIDERS: quad9
      FIREWALL: "on"
      FIREWALL_VPN_INPUT_PORTS:
      OPENVPN_USER: "${OPENVPN_USER}"
      OPENVPN_VERBOSITY: 2
      PGID: "${PGID}"
      PUID: "${PUID}"
      SERVER_HOSTNAME: "${SERVER_HOSTNAME}"
      TZ: "${TZ}"
      VPNSP: mullvad
    volumes:
      - ./gluetun:/gluetun

  monerod:
    container_name: monerod
    image: xmrto/monero:v0.17.2.0
    restart: unless-stopped
    command:
      - --data-dir=/data
    environment:
      LOG_LEVEL: 3
      P2P_BIND_IP: 0.0.0.0
      P2P_BIND_PORT: 28080
      RPC_BIND_IP: 0.0.0.0
      RPC_BIND_PORT: 28081
      RPC_PASSWD: ""
      RPC_USER: ""
      USE_TOR: "YES"
      USE_TORSOCKS: "YES"
      USER_ID: "${PUID}"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./bitmonero.conf:/data/bitmonero.conf:ro
      - monero:/data

volumes:

  monero:
    driver: local
    driver_opts:
      device: :/Monero
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
