apiVersion: 1

datasources:

  - name: influxdb-telegraf
    access: proxy
    database: telegraf
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      httpMode: GET

  - name: prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    editable: true
