version: "3"

networks:

  default:
    name: solana

services:

  solana:
    container_name: solana
    image: solanalabs/solana:stable
    ports:
      - 8000:8000/udp # tvu
      - 8001:8001/tcp # entrypoint
      - 8001:8001/udp # gossip
      - 8002:8002/udp # tvu_forwards
      - 8003:8003/udp # tpu
      - 8004:8004/udp # tpu_forwards
      - 8005:8005/udp # retransmit
      - 8006:8006/udp # repair
      - 8007:8007/udp # serve_repair
      - 8008:8008/udp # broadcast
      - 8899:8899/tcp # rpc http
      - 8900:8900/tcp # rpc pubsub
      - 9900:9900/tcp # faucet
    volumes:
      - solana:

volumes:

  solana:
    driver: local
    name: Solana
    driver_opts:
      device: :/Solana
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
