version: "3"

networks:

  default:
    name: hass

  traefik:
    external:
      name: traefik

services:

  hass:
    container_name: hass
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      # traefik.http.middlewares.allow-embedding.headers.contentSecurityPolicy: "frame-ancestors organizr.${DOMAIN}"
      traefik.http.services.hass.loadbalancer.server.port: 8123
    networks:
      - default
      - traefik
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
