version: "3"

networks:

  default:
    name: pihole-net
    ipam:
      config:
        - subnet: 172.16.0.0/16

  traefik-net:
    external:
      name: traefik-net

services:

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:v5.8.1
    restart: unless-stopped
    dns:
      - 127.0.0.1 # this Pihole
      - 192.168.1.1 # OPNsense Unbound
    environment:
      ADMIN_EMAIL: "pihole@${DOMAIN}"
      DNS_BOGUS_PRIV: "false"
      DNS_FQDN_REQUIRED: "false"
      DNSMASQ_LISTENING: all
      DNSSEC: "false" # DNSSEC handled by OPNsense Unbound
      PIHOLE_DNS_: 192.168.1.1 # OPNsense Unbound
      QUERY_LOGGING: "true"
      REV_SERVER: "true"
      REV_SERVER_CIDR: 192.168.1.0/24
      REV_SERVER_DOMAIN: lan
      REV_SERVER_TARGET: 192.168.1.1 # OPNsense DHCP
      ServerIP: "${ServerIP}" # host IP
      TEMPERATUREUNIT: c
      TZ: "${TZ}"
      VIRTUAL_HOST: "pihole.${DOMAIN}"
      WEBPASSWORD: "${WEBPASSWORD}"
      WEBUIBOXEDLAYOUT: traditional
    labels:
      traefik.enable: true
      traefik.http.routers.pihole-api.rule: Host(`pihole.${DOMAIN}`) && Path(`/admin/api.php`)
      traefik.http.routers.pihole.middlewares: authelia, error-pages, whitelist-lan@file
      traefik.http.services.pihole.loadbalancer.server.port: 80
    networks:
      default:
        ipv4_address: 172.16.0.100
      traefik-net:
    ports:
      - "${ServerIP}:53:53/tcp"
      - "${ServerIP}:53:53/udp"
    volumes:
      - ./dnsmasq.d:/etc/dnsmasq.d
      - ./pihole:/etc/pihole
