version: "3"

networks:

  default:
    name: chevereto-net

  traefik-net:
    external:
      name: traefik-net

services:

  chevereto:
    container_name: chevereto
    image: chevereto/chevereto:latest-httpd-php
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      CHEVERETO_DB_DRIVER: pgsql
      CHEVERETO_DB_HOST: chevereto-db
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PASS: "${MYSQL_PASSWORD}"
      CHEVERETO_DB_PORT: 5432
      CHEVERETO_DB_TABLE_PREFIX: chv_
      CHEVERETO_DB_USER: "${MYSQL_USER}"
      CHEVERETO_SOFTWARE: chevereto-free
      CHEVERETO_TAG: 1.3.0
    labels:
      traefik.enable: true
      traefik.http.routers.chvereto.middlewares: error-pages
      traefik.http.services.chevereto.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./images:/var/www/html/images
      - ./importing:/app/chevereto/importing
      - photos:/photos

  db:
    container_name: chevereto-db
    image: mariadb:10.6.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${MYSQL_USER}"
    volumes:
      - ./db:/var/lib/mysql

volumes:

  photos:
    external:
      name: photos
