version: "3"

networks:

  default:
    name: chevereto-net

  traefik-net:
    external:
      name: traefik-net

services:

  chevereto:
    container_name: chevereto
    image: chevereto/chevereto:latest-httpd-php
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      CHEVERETO_DB_DRIVER: pgsql
      CHEVERETO_DB_HOST: chevereto-db
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PASS: "${MYSQL_PASSWORD}"
      CHEVERETO_DB_PORT: 5432
      CHEVERETO_DB_TABLE_PREFIX: chv_
      CHEVERETO_DB_USER: "${MYSQL_USER}"
      CHEVERETO_SOFTWARE: chevereto-free
      CHEVERETO_TAG: 1.3.0
    labels:
      traefik.enable: true
      traefik.http.routers.chvereto.middlewares: error-pages
      traefik.http.services.chevereto.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./images:/var/www/html/images
      - ./importing:/app/chevereto/importing
      - photos:/photos

  db:
    container_name: chevereto-db
    image: linuxserver/mariadb:alpine-10.5.9-r0-ls14
    restart: always
    environment:
      MYSQL_DATABASE: chevereto
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: chevereto
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    volumes:
      - ./db:/config

volumes:

  photos:
    driver: local
    driver_opts:
      device: :/Photos
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
