version: "3"

networks:

  default:
    name: speedtest

  traefik:
    external:
      name: traefik

services:

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    restart: unless-stopped
    environment:
      AUTH: "true"
      OOKLA_EULA_GDPR: "true"
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.speedtest.middlewares: authelia, error-pages
      traefik.http.services.speedtest.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./config:/config
