global:
  evaluation_interval: 10s
  scrape_interval: 10s

scrape_configs:

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: geth_mainnet
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["geth_mainnet:6060"]

  - job_name: geth_testnet
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["geth_testnet:6060"]

  - job_name: jaeger
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: jupyter
    static_configs: 
      - targets: ["jupyter:8888"]

  - job_name: lighthoust_testnet
    static_configs:
      - targets: ["lighthouse_testnet:5054"]

  - job_name: miniflux
    scrape_interval: 10m
    static_configs:
      - targets: ["miniflux:8080"]

  - job_name: ping
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: "ping-exporter:9115"

  - job_name: polkadot
    static_configs:
      - targets: ["polkadot:9615"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: prysm_mainnet_beacon
  #   static_configs:
  #     - targets: ["prysm_mainnet_beacon_1:8080"]

  # - job_name: prysm_mainnet_validator
  #   static_configs:
  #     - targets: ["prysm_mainnet_validator_1:8081"]

  - job_name: prysm_testnet_beacon
    static_configs:
      - targets: ["prysm_testnet_beacon_1:8080"]

  - job_name: prysm_testnet_validator
    static_configs:
      - targets: ["prysm_testnet_validator_1:8081"]

  - job_name: speedtest
    scrape_interval: 30m
    scrape_timeout: 1m
    static_configs:
      - targets: ["speedtest-exporter:9798"]
    tls_config:
      insecure_skip_verify: true

  - job_name: teku_testnet
    static_configs:
      - targets: ["teku_testnet:8008"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik:8082"]

  - job_name: watchtower
    bearer_token: watchtower
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["watchtower:8080"]
