global:
  evaluation_interval: 10s
  scrape_interval: 10s

scrape_configs:

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: eth-mainnet-beacon
    static_configs:
      - targets: ["eth_mainnet_beacon_1:8080"]

  - job_name: eth-mainnet-geth
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["eth_mainnet_geth_1:6060"]

  - job_name: eth-mainnet-validator
    static_configs:
      - targets: ["eth_mainnet_validator_1:8081"]

  - job_name: eth-testnet-beacon
    static_configs:
      - targets: ["eth_testnet_beacon_1:8080"]

  - job_name: eth-testnet-geth
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["eth_testnet_geth_1:6060"]

  - job_name: eth-testnet-validator
    static_configs:
      - targets: ["eth_testnet_validator_1:8081"]

  - job_name: jaeger
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: jupyter
    static_configs:
      - targets: ["jupyter:8888"]

  - job_name: miniflux
    scrape_interval: 10m
    static_configs:
      - targets: ["miniflux:8080"]

  - job_name: ping
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: "ping-exporter:9115"

  - job_name: polkadot
    static_configs:
      - targets: ["polkadot:9615"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: speedtest
    scrape_interval: 30m
    scrape_timeout: 1m
    static_configs:
      - targets: ["speedtest-exporter:9798"]
    tls_config:
      insecure_skip_verify: true

  - job_name: traefik
    static_configs:
      - targets: ["traefik:8082"]

  - job_name: watchtower
    bearer_token: watchtower
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["watchtower:8080"]
