# logo: "assets/logo.png"
columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true
footer:
header: true # Set to false to hide the header
icon: "fas fa-skull-crossbones" # fontawesome.com/icons
subtitle: "Homer"
title: "Homelab"

theme: default # 'default' or one of the themes available in 'src/assets/themes'
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# message:
#   # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
#   # mapping: # allows to map fields from the remote format to the one expected by Homer
#   #   title: 'id' # use value from field 'id' as title
#   #   content: 'value' # value from field 'value' as content
#   # refreshInterval: 10000 # Optional: time interval to refresh message
#   #
#   # Real example using chucknorris.io for showing Chuck Norris facts as messages:
#   # url: https://api.chucknorris.io/jokes/random
#   # mapping:
#   #   title: 'id'
#   #   content: 'value'
#   # refreshInterval: 10000
#   style: "is-warning"
#   title: "Optional message!"
#   icon: "fa fa-exclamation-triangle"
#   content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

links:

  - name: "Link 1"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html tag target attribute

  # this will link to a second homer page that will load config from page2.yml
  # and keep default config values as in config.yml file see url field and
  # assets/page.yml used in this example:
  - name: "Second Page"
    icon: "fas fa-file-alt"
    url: "#page2"

services:

  - name: "Media"
    icon: "fas fa-code-branch"
    # logo: "path/to/logo"
    items:

      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        # icon: "fab fa-jenkins"
        subtitle: "Bookmark example"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html tag target attribute

      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        tagstyle: "is-success" # Optional tagstyle
        url: "#"

  - name: "System"
    icon: "fas fa-heartbeat"
    items:

      - name: "Pi-hole"
        # background: red # optional color for card to set color directly without custom stylesheet
        # class: "green" # optional custom CSS class for card, useful with custom stylesheet
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        logo: "assets/tools/sample.png"
        tag: "other"
        target: "_blank"
        type: "PiHole"
        url: "http://pihole.spencerboucher.com"
