version: "3"

networks:

  default:
    name: tor

services:

  obfs4-bridge:
    image: thetorproject/obfs4-bridge:latest
    container_name: tor
    restart: unless-stopped
    environment:
      EMAIL: "${EMAIL}"
      OR_PORT: "${OR_PORT}"
      PT_PORT: "${PT_PORT}"
    ports:
      - "${OR_PORT}:${OR_PORT}"
      - "${PT_PORT}:${PT_PORT}"
    volumes:
      - data:/var/lib/tor

volumes:

  data:
    name: tor-datadir
