version: "3"

networks:

  default:
    name: nextcloud

  traefik:
    external:
      name: traefik

services:

  cron:
    container_name: nextcloud-cron
    entrypoint: /cron.sh
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/data
      - ./nextcloud:/var/www/html

  db:
    container_name: nextcloud-db
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: nextcloud
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/pgdata:/var/lib/postgresql/data

  nextcloud:
    container_name: nextcloud
    image: nextcloud:21
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NEXTCLOUD_ADMIN_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"
      NEXTCLOUD_ADMIN_USER: "${NEXTCLOUD_ADMIN_USER}"
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${DOMAIN}
      OVERWRITEPROTOCOL: https
      PHP_MEMORY_LIMIT: 4G
      PHP_UPLOAD_LIMIT: 4G
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextcloud-db
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: nextcloud
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: "${REDIS_HOST_PASSWORD}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_NAME: "${SMTP_NAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: STARTTLS
    labels:
      traefik.enable: true
      traefik.http.middlewares.dav.redirectregex.permanent: true
      traefik.http.middlewares.dav.redirectregex.regex: "https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.dav.redirectregex.replacement: "https://$${1}/remote.php/dav/"
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./data:/data
      - ./nextcloud:/var/www/html
      - documents:/documents
      - photos:/photos

  redis:
    command: redis-server --requirepass "${REDIS_HOST_PASSWORD}"
    container_name: nextcloud-redis
    image: redis:6.2.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis:/data

volumes:

  documents:
    driver: local
    name: documents
    driver_opts:
      device: :/Documents
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  photos:
    driver: local
    name: photos
    driver_opts:
      device: :/Photos
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  redis:
    name: nextcloud-redis
