version: "3"

networks:

  default:
    name: nextcloud-net

  traefik-net:
    external:
      name: traefik-net

services:

  cron:
    container_name: nextcloud-cron
    entrypoint: /cron.sh
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/var/www/html
      - ./data:/data

  db:
    container_name: nextcloud-db
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/pgdata:/var/lib/postgresql/data

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NEXTCLOUD_ADMIN_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"
      NEXTCLOUD_ADMIN_USER: "${NEXTCLOUD_ADMIN_USER}"
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: "${NEXTCLOUD_TRUSTED_DOMAINS}"
      OVERWRITEPROTOCOL: https
      PHP_UPLOAD_LIMIT: 2G
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextcloud-db
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: "${REDIS_HOST_PASSWORD}"
    labels:
      traefik.enable: true
      traefik.http.middlewares.dav.redirectregex.permanent: true
      traefik.http.middlewares.dav.redirectregex.regex: ^https://(.*)/.well-known/(card|cal)dav
      traefik.http.middlewares.dav.redirectregex.replacement: https://$${1}/remote.php/dav/
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./app:/var/www/html
      - ./data:/data
      - calibre:/calibre
      - documents:/documents
      - photos:/photos

  redis:
    command: redis-server --requirepass "${REDIS_HOST_PASSWORD}"
    container_name: nextcloud-redis
    image: redis:6.2.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:

  calibre:
    driver: local
    driver_opts:
      device: :/Calibre
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  documents:
    driver: local
    driver_opts:
      device: :/Documents
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  photos:
    driver: local
    driver_opts:
      device: :/Photos
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
