version: "3"

networks:

  default:
    name: grocy

  traefik:
    external:
      name: traefik

services:

  grocy:
    container_name: grocy
    image: linuxserver/grocy:version-v2.7.1 # last version with android support
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.grocy-api.rule: Host(`grocy.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.grocy.middlewares: authelia, error-pages
      traefik.http.services.ghost.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./config:/config
