version: "3"

networks:

  default:
    name: photostructure

  traefik:
    external:
      name: traefik

# https://photostructure.com/server/photostructure-for-docker-compose/

services:

  photostructure:
    container_name: photostructure
    image: photostructure/server:stable
    restart: unless-stopped
    environment:
      PS_COPY_ASSETS_TO_LIBRARY: "true" # copy to /ps/library
      PS_FORCE_LOCAL_DB_REPLICA: "true" # needed for remote volume
      PS_LOG_COLOR: "true"
      PS_LOG_LEVEL: debug
      PS_REPORT_ERRORS: "false"
      PS_SCAN_ALL_DRIVES: "true" # scan every attached volume
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.photostructure.middlewares: authelia, error-pages
      traefik.http.services.photostructure.loadbalancer.server.port: 1787
    networks:
      - default
      - traefik
    volumes:
      - ./config:/ps/config
      - ./tmp:/ps/tmp
      - /var/log/photostructure:/ps/logs
      - import:/import # import volume (local)
      - photos:/ps/library # permanent volume (NAS)

volumes:

  photos:
    driver: local
    name: photostructure
    driver_opts:
      device: :/Photos/photostructure
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  import:
    name: photostructure-import
