http:
  routers:

    homeassistant:
      rule: Host(`hass.{{ env "DOMAIN" }}`)
      middlewares: error-pages@docker
      service: homeassistant

    netdata:
      rule: Host(`netdata.{{ env "DOMAIN" }}`)
      middlewares: authelia@docker, error-pages@docker
      service: netdata

    plex:
      rule: Host(`plex.{{ env "DOMAIN" }}`)
      service: plex

  services:

    homeassistant:
      loadBalancer:
        servers:
          - url: http://hass.lan:8123

    netdata:
      loadBalancer:
        servers:
          - url: http://opnsense.lan:19999
    plex:
      loadBalancer:
        servers:
          - url: http://qnap.lan:32400
