http:
  routers:

    plex:
      rule: Host(`plex.{{ env "DOMAIN" }}`)
      service: plex

  services:

    plex:
      loadBalancer:
        servers:
          - url: http://{{ env "QNAP_IP" }}:32400
