http:
  routers:

    plex:
      rule: Host(`plex.{{ env "DOMAIN" }}`)
      service: plex

    qnap:
      middlewares:
        - whitelist-lan@file
      rule: Host(`qnap.{{ env "DOMAIN" }}`)
      service: qnap

  services:

    plex:
      loadBalancer:
        servers:
          - url: http://{{ env "QNAP_IP" }}:32400

    qnap:
      loadBalancer:
        servers:
          - url: http://{{ env "QNAP_IP" }}:8080
