version: "3"

networks:

  default:
    name: lighthouse_testnet

  geth_testnet:
    external:
      name: geth_testnet

  prometheus:
    external:
      name: prometheus

services:

  lighthouse:
    container_name: lighthouse_testnet
    dns: [ 192.168.1.1 ] # unbound
    image: sigp/lighthouse:latest
    command:
      - lighthouse
      - beacon_node
      - --datadir=/data
      - --eth1-endpoints=http://geth_testnet:8546, ${INFURA_URL}
      - --graffiti=${GRAFFITI}
      - --http
      - --http-address=0.0.0.0
      - --metrics # prometheus
      - --metrics-address=0.0.0.0
      - --network=pyrmont
      - --port=9002 # default 9000
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - default
      - geth_testnet
      - prometheus
    ports:
      - 9002:9002
    volumes:
      - lighthouse:/data

volumes:

  beaconchain:
    driver: local
    driver_opts:
      device: :/Lighthouse_Pyrmont
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  lighthouse:
    name: lighthouse_testnet
