version: "3"

networks:

  default:
    name: linkding

  traefik:
    external:
      name: traefik

services:

    linkding:
      container_name: linkding
      image: sissbruecker/linkding:latest
      restart: unless-stopped
      networks:
        - default
        - traefik
      labels:
        traefik.enable: true
        traefik.http.routers.linkding.middlewares: authelia
        traefik.http.services.linkding.loadbalancer.server.port: 9090
      volumes:
        - ./data:/etc/linkding/data
