version: "3"

networks:

  default:
    name: homer

  traefik:
    external:
      name: traefik

services:

  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    environment:
      GID: "${PGID}"
      UID: "${PUID}"
    labels:
      traefik.enable: true
      traefik.http.routers.homer.middlewares: authelia, error-pages
      traefik.http.services.homer.loadbalancer.server.port: 8080
    networks:
      - default
      - traefik
    volumes:
      - ./assets:/www/assets
