version: "3"

networks:

  default:
    name: homer-net

  traefik-net:
    external:
      name: traefik-net

services:

  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    environment:
      GID: ${PGID}
      UID: ${PUID}
    labels:
      traefik.enable: true
      traefik.http.routers.homer.middlewares: authelia
      traefik.http.services.homer.loadbalancer.server.port: 8080
    networks:
      - default
      - traefik-net
    volumes:
      - ./assets:/www/assets
