version: "3"

networks:

  default:
    name: calibre

  deluge-servarr:
    external:
      name: deluge-servarr

  traefik:
    external:
      name: traefik

  servarr:
    external:
      name: servarr

services:

  calibre:
    container_name: calibre
    image: linuxserver/calibre:latest
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.calibre.middlewares: authelia, error-pages, whitelist-lan@file
      traefik.http.routers.calibre.rule: "Host(`calibre.${DOMAIN}`)"
      traefik.http.services.calibre.loadbalancer.server.port: 8080
    networks:
      - default
      - traefik
    ports:
      - 8081:8081 # server
      - 9090:9090 # local discovery
    volumes:
      - ./calibre:/config
      - "calibre:/config/Calibre Library"

  calibre-web:
    container_name: calibre-web
    image: linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.middlewares.allow-embedding.headers.contentSecurityPolicy: "frame-ancestors organizr.${DOMAIN}"
      traefik.http.routers.calibre-web-opds.rule: Host(`books.${DOMAIN}`) && PathPrefix(`/opds`)
      traefik.http.routers.calibre-web.middlewares: allow-embedding, authelia, error-pages
      traefik.http.routers.calibre-web.rule: "Host(`books.${DOMAIN}`)"
      traefik.http.services.calibre-web.loadbalancer.server.port: 8083
    networks:
      - default
      - traefik
    volumes:
      - ./calibre-web:/config
      - calibre:/calibre

  readarr:
    container_name: readarr
    image: hotio/readarr:nightly
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: 002
    labels:
      traefik.enable: true
      traefik.http.routers.readarr.middlewares: authelia, error-pages
      traefik.http.services.readarr.loadbalancer.server.port: 8787
    networks:
      - default
      - deluge-servarr
      - servarr
      - traefik
    volumes:
      - ./readarr:/config
      - calibre:/calibre
      - downloads:/downloads

volumes:

  calibre:

  downloads:
    external: true
    name: downloads
