{
 "title": "Deluge",
 "description": "A Deluge statistics dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Torrents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"total\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Downloading",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"downloading\"}"
    }
   ]
  },
  {
   "title": "Seeding",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"seeding\"}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"error\"}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "deluge_torrents{state=\"paused\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "deluge_libtorrent_peers" }
   ]
  },
  {
   "title": "Current ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_libtorrent_upload_bytes_total{type=\"payload\"}/deluge_libtorrent_download_bytes_total{type=\"payload\"}"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(deluge_libtorrent_upload_bytes_total{type=\"payload\"}[30s])",
     "legendFormat": "Upload"
    },
    {
     "expr": "irate(deluge_libtorrent_download_bytes_total{type=\"payload\"}[30s])*-1",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_libtorrent_download_bytes_total{type=\"payload\"}"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "deluge_libtorrent_upload_bytes_total{type=\"payload\"}"
    }
   ]
  }
 ]
}