{
 "title": "Miniflux",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "Feeds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(miniflux_feeds{status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(miniflux_feeds{status=\"enabled\"})",
     "legendFormat": "Enabled"
    },
    { "expr": "max(miniflux_broken_feeds)", "legendFormat": "Broken" },
    {
     "expr": "max(miniflux_feeds{status=\"disabled\"})",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "Entries by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(miniflux_entries{status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(miniflux_entries{status=\"unread\"})",
     "legendFormat": "Unread"
    },
    {
     "expr": "max(miniflux_entries{status=\"read\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "max(miniflux_entries{status=\"removed\"})",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Scraper Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(miniflux_scraper_request_duration_bucket[5m])) by (le))",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Background Feed Refresh Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(miniflux_background_feed_refresh_duration_bucket[5m])) by (le))",
     "legendFormat": "Refresh Duration"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app=\"miniflux\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app=\"miniflux\"}",
     "legendFormat": "{{instance }} - Open File Descriptors"
    }
   ]
  }
 ]
}