{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\"}[5m])) by (le))",
     "legendFormat": "Latency over 5 min"
    }
   ]
  },
  {
   "title": "Per node latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Entrypoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Apdex score (over 5 min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.1\",code=\"200\"}[5m])) by (job) + sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\"}[5m])) by (job)) / 2 / sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
       "legendFormat": "Code 200"
      }
     ]
    },
    {
     "title": "Service total requests over 1min per entrypoint",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_requests_total[1m])) by (entrypoint)",
       "legendFormat": "{{ entrypoint }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Apdex score (over 5 min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(traefik_service_request_duration_seconds_bucket{le=\"0.1\",code=\"200\"}[5m])) by (job) + sum(rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",code=\"200\"}[5m])) by (job)) / 2 / sum(rate(traefik_service_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
       "legendFormat": "Code 200"
      }
     ]
    },
    {
     "title": "Service total requests over 1min per service",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total[1m])) by (service)",
       "legendFormat": "{{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Codes stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status code 2xx over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=~\"2..\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Status code 5xx over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=~\"5..\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Others statuses code over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code!~\"2..|5..\"}[5m])) by (method, code)",
       "legendFormat": "{{ method }} : {{code}}"
      }
     ]
    }
   ]
  }
 ]
}