version: "3"

networks:

  default:
    name: tfviewer-net

  traefik-net:
    external:
      name: traefik-net

services:

  tfviewer:
    container_name: tfviewer
    image: danielalvsaaker/tf-viewer:latest
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.tfviewer.middlewares: authelia, error-pages
      traefik.http.services.tfviewer.loadbalancer.server.port: 8080
    networks:
      - default
      - traefik-net
    volumes:
      - ./data:/data
