version: "3"

networks:

  default:
    name: deluge-net

  traefik-net:
    external:
      name: traefik-net

  prometheus-net:
    external:
      name: prometheus-net

services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
    environment:
      DELUGE_LOGLEVEL: INFO
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.deluge.middlewares: authelia, error-pages
      traefik.http.routers.deluge.rule: "Host(`deluge.${DOMAIN}`)"
      traefik.http.services.deluge.loadbalancer.server.port: 8112
    networks:
      - default
      - traefik-net
    volumes:
      - ./deluge:/config
      - ./downloads:/downloads
      - distros:/downloads/distros

volumes:

  distros:
    driver: local
    name: distros
    driver_opts:
      device: :/Distros
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
