version: "3"

networks:

  default:
    name: organizr

  calibre:
    external:
      name: calibre

  deluge-servarr:
    external:
      name: deluge-servarr

  servarr:
    external:
      name: servarr

  traefik:
    external:
      name: traefik

services:

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      branch: v2-master
      fpm: "true"
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.organizr.middlewares: authelia, error-pages
      traefik.http.services.organizr.loadbalancer.server.port: 80
    networks:
      - calibre
      - default
      - deluge-servarr
      - servarr
      - traefik
    volumes:
      - ./config:/config
