default_redirection_url: https://heimdall.spencerboucher.com
host: 0.0.0.0
port: 9091
theme: grey

access_control:
  default_policy: two_factor
  networks:
    - name: local
      networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

authentication_backend:
  file:
    path: /config/users_database.yml

# log:
#   file_path: /config/log/authelia.log
#   keep_stdout: true
#   level: debug

notifier:
  disable_startup_check: false
  smtp:
    disable_html_emails: true
    host: mail.privateemail.com
    port: 587
    sender: spencer@spencerboucher.com
    username: spencer@spencerboucher.com

session:
  domain: spencerboucher.com
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  name: authelia_session
  redis:
    host: authelia-redis
    port: 6379

regulation:
  ban_time: 300
  find_time: 120
  max_retries: 3

server:
  read_buffer_size: 8192
  write_buffer_size: 8192

storage:
  local:
    path: /config/db.sqlite3

totp:
  issuer: authelia.com
