access_control:
  default_policy: deny
  networks:
    - name: local
      networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  rules:
    - domain: "*.spencerboucher.com"
      policy: two_factor
      subject:
        - 'user:justmytwospence'
    - domain: books.spencerboucher.com
      policy: two_factor
      subject:
        - 'user:justmytwospence'
        - 'user:guest'
