version: "3"

networks:

  traefik:
    external:
      name: traefik

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.middlewares: authelia, error-pages
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
