version: "3"

networks:

  default:
    name: portainer-net

  traefik-net:
    external:
      name: traefik-net

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - default
      - traefik-net
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
