version: "3"

networks:

  default:
    name: servarr-net

  traefik-net:
    external:
      name: traefik-net

services:

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: authelia, error-pages
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
    networks:
      - default
      - traefik-net
    volumes:
      - ./bazarr:/config
      - multimedia:/multimedia

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      AUTO_UPDATE: "true"
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.jackett-api.rule: Host(`jackett.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.jackett.middlewares: authelia, error-pages
      traefik.http.services.jackett.loadbalancer.server.port: 9117
    networks:
      - default
      - traefik-net
    volumes:
      - ./jackett:/config

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: authelia, error-pages
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
    networks:
      - default
      - traefik-net
    volumes:
      - ./prowlarr:/config

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.radarr-api.rule: Host(`radarr.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.radarr.middlewares: authelia, error-pages
      traefik.http.services.radarr.loadbalancer.server.port: 7878
    networks:
      - default
      - traefik-net
    volumes:
      - ./radarr:/config
      - multimedia:/multimedia
      - ~/downloads:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-api.rule: Host(`sonarr.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.sonarr.middlewares: authelia, error-pages
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
    networks:
      - default
      - traefik-net
    volumes:
      - ./sonarr:/config
      - multimedia:/multimedia
      - ~/downloads:/downloads

volumes:

  multimedia:
    driver: local
    name: multimedia
    driver_opts:
      device: :/Multimedia
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
