version: "3"

networks:

  default:
    name: huginn

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: huginn-db
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: huginn
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: huginn
    healthcheck:
      test: ["CMD", "pg_isready", "-U", huginn]
    volumes:
      - db:/var/lib/postgresql/data

  huginn-threaded:
    command: /scripts/init bin/threaded.rb
    container_name: huginn-threaded
    image: huginn/huginn-single-process:latest
    restart: always
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: huginn-db
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: huginn

  huginn-web:
    container_name: huginn-web
    image: huginn/huginn-single-process:latest
    restart: unless-stopped
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: huginn-db
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: huginn
    labels:
      traefik.enable: true
      traefik.http.routers.huginn.rule: "Host(`huginn.${DOMAIN}`)"
      traefik.http.routers.huginn.middlewares: authelia, error-pages
      traefik.http.services.huginn.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik

volumes:

  db:
    name: huginn-db
