version: "3"

networks:

  default:
    name: ghost

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: ghost-db
    image: mariadb:10.6.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_PASSWORD: "${PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ghost
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "ghost", "-p${PASSWORD}" ]
    volumes:
      - ./db:/var/lib/mysql

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      # NODE_ENV: development
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: ghost-db
      database__connection__password: "${PASSWORD}"
      database__connection__user: ghost
      url: "https://blog.${DOMAIN}"
    labels:
      traefik.enable: true
      # traefik.http.routers.ghost-blog.middlewares: error-pages
      traefik.http.routers.ghost-blog.rule: "Host(`blog.${DOMAIN}`)"
      traefik.http.services.ghost.loadbalancer.server.port: 2368
      # blog redirect
      traefik.http.middlewares.blog-redirect.redirectregex.permanent: true
      traefik.http.middlewares.blog-redirect.redirectregex.regex: "^https://${DOMAIN}/(.*)"
      traefik.http.middlewares.blog-redirect.redirectregex.replacement: "https://blog.${DOMAIN}/$${1}"
      traefik.http.routers.ghost-naked.middlewares: blog-redirect #, error-pages
      traefik.http.routers.ghost-naked.rule: "Host(`${DOMAIN}`)"
      # admin
      # traefik.http.routers.ghost-admin.middlewares: authelia #, error-pages
      traefik.http.routers.ghost-admin.rule: Host(`blog.${DOMAIN}`) && PathPrefix(`/ghost`)
    networks:
      - default
      - traefik
    volumes:
      - ./content:/var/lib/ghost/content

volumes:

  ghost-db:
    name: ghost-db
