version: "3"

networks:

  default:
    name: wikijs-net

  traefik-net:
    external:
      name: traefik-net

services:

  db:
    container_name: wikijs-db
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/pgdata:/var/lib/postgresql/data

  wikijs:
    container_name: wikijs
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: wikijs-db
      DB_NAME: wikijs
      DB_PASS: "${POSTGRES_PASSWORD}"
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: "${POSTGRES_USER}"
    labels:
      traefik.enable: true
      traefik.http.routers.wikijs.middlewares: authelia, error-pages
      traefik.http.services.wikijs.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik-net
