version: "3"

networks:

  default:
    name: wikijs

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: wikijs_db
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: wikijs
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wikijs"]
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - db:/var/lib/postgresql/data

  wikijs:
    container_name: wikijs
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: wikijs_db
      DB_NAME: wikijs
      DB_PASS: "${PASSWORD}"
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: wikijs
    labels:
      traefik.enable: true
      traefik.http.routers.wikijs.middlewares: authelia, error-pages
      traefik.http.routers.wikijs.rule: "Host(`wiki.${DOMAIN}`)"
      traefik.http.services.wikijs.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik
    volumes:
      - data_content:/wiki/data/content

volumes:

  data_content:
  db:
