version: "3"

networks:

  default:
    name: servas

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: servas-db
    image: mariadb:10.7.3
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME}"
    volumes:
      - servas-db-data:/var/lib/mysql

  servas:
    container_name: servas
    image: beromir/servas
    restart: unless-stopped
    depends_on:
      - db
    labels:
      traefik.enable: true
      # traefik.http.routers.servas.middlewares: authelia, error-pages
      # traefik.http.routers.servas-api.rule: Host(`servas.${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.services.servas.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./.env:/var/www/html/.env

volumes:
  servas-db-data:
