version: "3"

networks:

  default:
    name: lazylibrarian-net

  deluge-net:
    external:
      name: deluge-net

  servarr-net:
    external:
      name: servarr-net

  traefik-net:
    external:
      name: traefik-net

services:

  lazylibrarian:
    container_name: lazylibrarian
    image: linuxserver/lazylibrarian:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.lazylibrarian-opds.rule: Host(`lazylibrarian.${DOMAIN}`) && Path(`/opds`)
      traefik.http.routers.lazylibrarian.middlewares: authelia
      traefik.http.services.lazylibrarian.loadbalancer.server.port: 5299
    networks:
      - default
      - traefik-net
    volumes:
      - ./config:/config
      - /mnt/ssd1/downloads:/downloads
      - calibre:/books

volumes:

  calibre:
    external:
      name: Calibre
