version: "3"

networks:

  default:
    name: syncthing-net

  traefik-net:
    external:
      name: traefik-net

services:

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
    networks:
      - default
      - traefik-net
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    volumes:
      - ./config:/var/syncthing
      - android:/var/syncthing/android

volumes:

  android:
    driver: local
    name: android
    driver_opts:
      device: :/Android
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
