version: "3"

networks:

  default:
    name: photoprism

  nextcloud:
    external:
      name: nextcloud

  traefik:
    external:
      name: traefik

services:

  db:
    image: postgres:13.2
    container_name: photoprism-db
    environment:
      POSTGRES_DB: photoprism
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: photoprism
    healthcheck:
      test: ["CMD", "pg_isready", "-U", photoprism]
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/pgdata:/var/lib/postgresql/data

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      db:
        condition: service_healthy
    environment:
      GID: "${GUID}"
      PHOTOPRISM_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PHOTOPRISM_DARKTABLE_PRESETS: "true"
      PHOTOPRISM_DATABASE_DRIVER: postgres
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      PHOTOPRISM_DATABASE_SERVER: photoprism-db:5432
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_FFMPEG_BUFFERS: 32
      PHOTOPRISM_FFMPEG_ENCODER: libx264
      PHOTOPRISM_HTTP_COMPRESSION: gzip # (none or gzip)
      PHOTOPRISM_ORIGINALS_LIMIT: 1000 # MB
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_SITE_CAPTION: ""
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_TITLE: PhotoPrism
      PHOTOPRISM_SITE_URL: "https://photoprism.${DOMAIN}"
      PHOTOPRISM_SPONSOR: "true"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_WORKERS: 2
      UID: "${PUID}"
    labels:
      traefik.enable: true
      traefik.http.routers.photoprism.middlewares: authelia, error-pages
      traefik.http.services.photoprism.loadbalancer.server.port: 2342
    networks:
      - default
      - nextcloud
      - traefik
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    volumes:
      - ./storage:/photoprism/storage # sidecar files
      - photos:/photoprism/originals # in-place photos

volumes:

  photos:
    external:
      name: photos
