version: "3"

networks:

  default:
    name: photoprism

  nextcloud:
    external:
      name: nextcloud

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: photoprism-db
    image: mariadb:10.5
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-lock-wait-timeout=50
      - --innodb-rollback-on-timeout=OFF
      - --max-connections=512
      - --port=4001
      - --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_DATABASE: photoprism
      MYSQL_PASSWORD: "${PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: photoprism
    volumes:
      - ./db:/var/lib/mysql

  # ofelia:
  #   container_name: photoprism-ophelia
  #   image: mcuadros/ofelia:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./jobs.ini:/etc/ofelia/config.ini
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - db
      # - ofelia
    environment:
      GID: "${GUID}"
      PHOTOPRISM_ADMIN_PASSWORD: "${PASSWORD}"
      PHOTOPRISM_AUTO_IMPORT: 60 # seconds
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: "${PASSWORD}"
      PHOTOPRISM_DATABASE_SERVER: photoprism-db:4001
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_DETECT_NSFW: "true"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_HTTP_COMPRESSION: gzip # (none or gzip)
      PHOTOPRISM_LOG_LEVEL: debug
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_SERVER_MODE: "debug"
      PHOTOPRISM_SITE_URL: "https://photoprism.${DOMAIN}"
      PHOTOPRISM_SPONSOR: "true"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_WORKERS: 6
      UID: "${PUID}"
    labels:
      traefik.enable: true
      traefik.http.routers.photoprism-webdav.rule: Host(`photoprism.${DOMAIN}`) && PathPrefix(`/import`, `/originals`)
      traefik.http.routers.photoprism.middlewares: authelia, error-pages
      traefik.http.services.photoprism.loadbalancer.server.port: 2342
    networks:
      - default
      - nextcloud
      - traefik
    volumes:
      # PhotoSync/Dolphin -> webdav -> import -> photos -> webdav -> nextcloud share
      - ./storage:/photoprism/storage # sidecar files (local)
      - import:/photoprism/import # import (local)
      - originals:/photoprism/originals # permanent files (NAS)

volumes:

  originals:
    driver: local
    name: photoprism-originals
    driver_opts:
      device: :/Photos/photoprism
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  import:
    name: photoprism-import
