version: "3"

networks:

  default:
    name: unmanic

services:

  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    ports:
      - 8888:8888
    volumes:
      - /share/Multimedia:/multimedia
