version: "3"

networks:

  default:
    name: rhasspy

  homeassistant:
    external:
      name: homeassistant

services:

  rhasspy:
    container_name: rhasspy
    command: --user-profiles /profiles --profile en
    image: rhasspy/rhasspy:latest
    restart: unless-stopped
    tty: true
    devices:
      - /dev/snd:/dev/snd
    networks:
      - default
      - home-assistant
    ports:
      - 12101:12101
    volumes:
      - ./profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
