version: "3"

networks:

  default:
    name: vpn-net

  pihole-net:
    external:
      name: pihole-net

  traefik-net:
    external:
      name: traefik-net

services:

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    dns:
      - 172.16.0.100 # pi-hole
    environment:
      ALLOWEDIPS: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
      PEERDNS: auto
      PEERS: "${PEERS}"
      PGID: "${PGID}"
      PUID: "${PUID}"
      SERVERPORT: 51820
      SERVERURL: "${DOMAIN}"
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.udp.routers.wireguard.entrypoints: wireguard
      traefik.udp.routers.wireguard.service: wireguard
      traefik.udp.services.wireguard.loadbalancer.server.port: 51820
    networks:
      - default
      - pihole-net
      - traefik-net
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
