version: "3"

networks:

  default:
    name: vpn-net

  pihole-net:
    external:
      name: pihole-net

  traefik-net:
    external:
      name: traefik-net

services:

  wireguard:
    container_name: vpn
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    dns:
      - 172.18.0.1 # pi-hole subnet gateway
    environment:
      ALLOWEDIPS: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      PEERDNS: auto
      PEERS: ${PEERS}
      PGID: ${PGID}
      PUID: ${PUID}
      SERVERPORT: 51820
      SERVERURL: wireguard.${DOMAIN}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.services.wireguard.loadbalancer.server.port: 51820
    networks:
      - default
      - pihole-net
      - traefik-net
    # ports:
    #   - 51820:51820/udp
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
