version: "3"

networks:

  default:
    name: bitcoin

  prometheus:
    external:
      name: prometheus

services:

  bitcoind:
    container_name: bitcoind
    image: kylemanna/bitcoind:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G # 2G recommended
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    ports:
      - 8332:8332 # rpc
      - 8333:8333 # p2p
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - ./shared:/shared
      - bitcoin:/bitcoin/.bitcoin

  electrs:
    build: electrs
    command: electrs
    container_name: electrs
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
    environment:
      # ELECTRS_COOKIE_FILE: /shared/.cookie
      ELECTRS_DAEMON_RPC_ADDR: bitcoind:8332
      ELECTRS_DB_DIR: /db
      ELECTRS_ELECTRUM_RPC_ADDR: 0.0.0.0:51001
      ELECTRS_JSONRPC_IMPORT: "true"
      ELECTRS_MONITORING_ADDR: 0.0.0.0:4224
      ELECTRS_VERBOSE: 4
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    networks:
      - default
      - prometheus
    ports:
      - 51001:51001
    volumes:
      - ./electrs:/etc/electrs
      - ./shared:/shared
      - electrs:/db

  # lightningd:
  #   container_name: lightningd
  #   image: elementsproject/lightningd:latest
  #   restart: unless-stopped
  #   command:
  #     - --daemon
  #     - --lightning-dir=/lightning
  #     - --log-file=/lightning/lightningd.log
  #     - --log-level=debug
  #     - --network=bitcoin
  #   volumes:
  #     - ./lightning:/lightning

volumes:

  bitcoin:
    driver: local
    name: bitcoin
    driver_opts:
      device: :/Bitcoin
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs

  electrs:
    driver: local
    name: electrs
    driver_opts:
      device: :/Electrs
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
