version: "3"

networks:

  default:
    name: bitcoin-net

services:

  bitcoind:
    container_name: bitcoind
    image: kylemanna/bitcoind:1.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G # 2G recommended
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    ports:
      - 8332:8332 # rpc
      - 8333:8333 # p2p
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf:ro
      - bitcoin:/bitcoin/.bitcoin

  # lnd:
  #   container_name: lnd
  #   image: lnzap/lnd:latest
  #   restart: unless-stopped
  #   command:
  #     - --bitcoin.active
  #     - --bitcoin.testnet
  #     - --debuglevel=info
  #     - --bitcoin.node=neutrino
  #     - --neutrino.connect=testnet1-btcd.zaphq.io
  #     - --neutrino.connect=testnet2-btcd.zaphq.io
  #     - --autopilot.active
  #     - --rpclisten=0.0.0.0:10009
  #   ports:
  #     - 9735:9735
  #     - 10009:10009
  #   volumes:
  #     - ./lightning:/lnd

volumes:

  bitcoin:
    driver: local
    name: bitcoin
    driver_opts:
      device: :/Bitcoin
      o: addr=192.168.1.3,nfsvers=4,rw
      type: nfs
