version: "3"

networks:

  default:
    name: monica

  traefik:
    external:
      name: traefik

services:

  db:
    container_name: monica-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: monica
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: monica
    volumes:
      - monica-db:/var/lib/mysql

  monica:
    container_name: monica
    image: monica:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      APP_DEFAULT_TIMEZONE: "${TZ}"
      APP_ENV: production
      APP_KEY: "${APP_KEY}"
      APP_TRUSTED_PROXIES: "*"
      APP_URL: "https://monica.${DOMAIN}"
      DB_CONNECTION: mysql
      DB_DATABASE: monica
      DB_HOST: monica-db
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_USERNAME: monica
    labels:
      traefik.enable: true
      traefik.http.routers.monica.middlewares: authelia, error-pages
      traefik.http.services.monica.loadbalancer.server.port: 80
    networks:
      - default
      - traefik
    volumes:
      - ./data:/var/www/html/storage

volumes:

  monica-db:
    name: monica-db

