version: "3"

networks:

  default:
    name: filerun-net

  traefik-net:
    external:
      name: traefik-net

services:

  db:
    container_name: filerun-db
    image: mariadb:10.6.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${MYSQL_USER}"
    volumes:
      - ./db:/var/lib/mysql

  filerun:
    container_name: filerun
    image: afian/filerun
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      FR_DB_HOST: db
      FR_DB_NAME: filerun
      FR_DB_PASS: "${MYSQL_PASSWORD}"
      FR_DB_PORT: 3306
      FR_DB_USER: filerun
    labels:
      traefik.enable: true
      traefik.http.routers.filerun.middlewares: authelia, error-pages
      traefik.http.services.filerun.loadbalancer.server.port: 80
    networks:
      - default
      - traefik-net
    volumes:
      - ./filerun:/var/www/html
      - ./user-files:/user-files
